services:
  weather.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire:18889
      OTEL_EXPORTER_OTLP_HEADERS: x-otlp-api-key=${OTLP_PRIMARYAPIKEY}
      Authentication__Schemes__Bearer__Authority: http://keycloak:8080/realms/weather
      Authentication__Schemes__Bearer__RequireHttpsMetadata: false
      Authentication__Schemes__Bearer__ValidIssuer: https://keycloak.docker.internal/realms/weather
      Authentication__Schemes__Bearer__ValidAudiences__0: swagger
      Authentication__Swagger__ClientId: swagger
      Authentication__Swagger__AuthorizationUrl: https://keycloak.docker.internal/realms/weather/protocol/openid-connect/auth
      Authentication__Swagger__TokenUrl: https://keycloak.docker.internal/realms/weather/protocol/openid-connect/token
      Authentication__Swagger__Scopes__0: openid
      OpenWeatherMap__BaseUrl: https://api.openweathermap.org/data/2.5/
      OutboxMessageProcessor__Period: 00:00:15
      OutboxMessageProcessor__MaximumConcurrentMessage: null
      Email__DefaultFrom: random@acme.com
      Email__Smtp__Host: papercut
      Email__Smtp__Port: 25

  aspire:
    environment:
      DASHBOARD__OTLP__AUTHMODE: ApiKey
      DASHBOARD__OTLP__PRIMARYAPIKEY: ${OTLP_PRIMARYAPIKEY}

  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  keycloak: 
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL_DATABASE: ${DB_NAME}
      KC_DB_SCHEMA: keycloak
      KC_PROXY: edge
      KC_HTTP_ENABLE: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME: keycloak.docker.internal