http:
  routers:
    traefik:
      rule: "Host(`traefik.docker.internal`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.internal"
            sans:
              - "*.docker.internal"

tls:
  certificates:
    - certFile: "/etc/traefik/ssl/local-cert.pem"
      keyFile: "/etc/traefik/ssl/local-key.pem"